export const initialQuizCategory = [
    {
        category: 'JavaScript',
        description: 'Basic JavaScript quiz covering variables, loops, and functions.',
        timeLimit: 10,
        createdBy: 'admin',
    },
    {
        category: 'Python',
        description: 'Intermediate Python quiz focusing on data structures and algorithms.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'Linux',
        description: 'Advanced Linux quiz about shell scripting and system administration.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Data Structures and Algorithms',
        description: 'Quiz on DSA concepts like trees, graphs, and sorting algorithms.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Operating Systems',
        description: 'Introduction to OS concepts like processes, threads, and memory management.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'Databases',
        description: 'Intermediate quiz covering SQL queries, normalization, and relational databases.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Computer Networks',
        description: 'Advanced quiz on networking concepts like TCP/IP, DNS, routing protocols, and security.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Software Engineering',
        description: 'Quiz on software development methodologies, testing, and project management.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Artificial Intelligence',
        description: 'Advanced AI quiz focusing on machine learning, neural networks, and deep learning.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Cybersecurity',
        description: 'Intermediate quiz on security protocols, encryption, and ethical hacking.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Cloud Computing',
        description: 'Quiz on cloud services, cloud architectures, and deployment models.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Blockchain',
        description: 'Advanced quiz on blockchain technology, consensus algorithms, and cryptography.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Big Data',
        description: 'Advanced quiz on big data technologies, data processing frameworks, and Hadoop.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Web Development',
        description: 'Introduction to web development concepts like HTML, CSS, and JavaScript.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'Mobile App Development',
        description: 'Quiz on mobile app development using Android or iOS frameworks.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Machine Learning',
        description: 'Advanced quiz on machine learning algorithms, model evaluation, and applications.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Parallel Computing',
        description: 'Advanced quiz on parallel computing techniques, architectures, and algorithms.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Cryptography',
        description: 'Intermediate quiz on encryption algorithms, hashing, and cryptographic protocols.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Computer Graphics',
        description: 'Advanced quiz on computer graphics techniques, rendering, and 3D modeling.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Quantum Computing',
        description: 'Advanced quiz on quantum algorithms, qubits, and quantum gates.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Theory of Computation',
        description: 'Quiz on automata theory, regular languages, and Turing machines.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Compilers',
        description: 'Advanced quiz on compiler design, parsing techniques, and optimization.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Natural Language Processing',
        description: 'Advanced quiz on NLP techniques, tokenization, and sentiment analysis.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Robotics',
        description: 'Intermediate quiz on robot design, kinematics, and control systems.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Augmented Reality',
        description: 'Quiz on AR concepts, applications, and development frameworks.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Game Development',
        description: 'Intermediate quiz on game mechanics, engines, and interactive design.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Distributed Systems',
        description: 'Advanced quiz on distributed algorithms, consistency, and fault tolerance.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Edge Computing',
        description: 'Advanced quiz on edge computing architecture and applications.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'IoT (Internet of Things)',
        description: 'Intermediate quiz on IoT devices, protocols, and cloud integration.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Data Science',
        description: 'Advanced quiz on data analysis, visualization, and statistical modeling.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Computer Vision',
        description: 'Advanced quiz on image processing, feature extraction, and computer vision algorithms.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Cloud Security',
        description: 'Intermediate quiz on securing cloud services, encryption, and identity management.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Virtualization',
        description: 'Quiz on virtualization technologies, hypervisors, and cloud computing integration.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'DevOps',
        description: 'Intermediate quiz on DevOps practices, CI/CD pipelines, and containerization.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'API Development',
        description: 'Intermediate quiz on RESTful API design, endpoints, and security.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Microservices',
        description: 'Advanced quiz on microservices architecture, containerization, and service orchestration.',
        timeLimit: 30,
        createdBy: 'admin',
    },
    {
        category: 'Agile Methodology',
        description: 'Quiz on Agile practices, Scrum, and project management.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Version Control',
        description: 'Introduction to version control systems, focusing on Git and GitHub.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'C',
        description: 'Basic C programming quiz covering syntax, loops, and functions.',
        timeLimit: 10,
        createdBy: 'admin',
    },
    {
        category: 'C++',
        description: 'Intermediate C++ quiz focusing on OOP concepts, STL, and algorithms.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'Rust',
        description: 'Advanced Rust quiz on memory safety, ownership, and concurrency.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Go',
        description: 'Intermediate Go quiz covering goroutines, channels, and standard library.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Swift',
        description: 'Quiz on Swift programming for iOS development and SwiftUI basics.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'MySQL',
        description: 'Intermediate MySQL quiz covering queries, joins, and database design.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'MongoDB',
        description: 'Quiz on MongoDB basics, aggregation framework, and NoSQL concepts.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Linked List',
        description: 'Basic quiz on linked list operations like insertion, deletion, and traversal.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'Array',
        description: 'Quiz on array manipulation, searching, and sorting algorithms.',
        timeLimit: 15,
        createdBy: 'admin',
    },
    {
        category: 'Stack',
        description: 'Intermediate quiz on stack operations, applications, and implementation.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Queue',
        description: 'Quiz on queue operations, circular queue, and priority queue.',
        timeLimit: 20,
        createdBy: 'admin',
    },
    {
        category: 'Graph',
        description: 'Advanced quiz on graph algorithms like BFS, DFS, and shortest path.',
        timeLimit: 25,
        createdBy: 'admin',
    },
    {
        category: 'Dynamic Programming',
        description: 'Advanced quiz on dynamic programming concepts like memoization, tabulation, and optimization problems.',
        timeLimit: 30,
        createdBy: 'admin',
    },
];


export const initialQuestions = [
    

]